### ISSUE TITLE
No sound :(

### ISSUE THREAD

**Issue by ghost** [lrussell887/Debian-for-WM8505-Netbooks#2]
So, I have one of these netbooks (with the WM8505), unbranded, and when I saw this I decided to give it a try, and everything actually worked really amazingly! It's seriously amazing what you can do on these tiny little netbooks. There's just one thing missing, and it's the audio... I spent a little while trying to get audio working, and I found (apparently) that these netbooks use the ES8328 codec driver (maybe?). 

I compiled the kernel module for this, and I modprobed it on the netbook, but there's still no sound cards detected. Apparently it might also use a VT1613, but I don't really understand how it works or how to compile it, so I'm at a loss. I looked around and some people are saying that sound worked on earlier versions of the kernel, so why doesn't sound work now? 

Thanks though for seriously creating such a fully featured install of Debian on these things though, it's really awesome

**Comment by lrussell887** [comment]
I honestly forgot I had made this project. 😅 I was never able to get built-in audio working either, but USB sound cards worked fine. Unfortunately I don't have access to any of my old netbooks at the moment.

The kernel I used was taken from [this repository](https://github.com/wh0/bookconfig), incorporating whatever changes were needed. I believe I was able to get a mainline kernel to boot, but without display or keyboard, it wasn't particularly usable.

If I recall correctly those older builds used an Android kernel (?) and bootstrapped an OS on top of it. If you do some digging you might find a Debian Lenny build like that from the time, but it was old even when I found it.

Admittedly I'm not all _that_ Linux-savvy, so I wouldn't know where to go from here. This was really more of a test to see if I could even build a kernel, and maybe make use of something collecting dust in a drawer. 😂

**Comment by ghost** [comment]
Lol it's fine, I mean to be honest I kind of just had the same thought and dug through my closet and found this old thing and was wondering if it could do literally anything, and when I was your repo I was completely surprised that someone could do this much. I'll see what I can do though, but yea, I don't think I'm that much Linux-savvy either to do anything, lol

**Comment by lrussell887** [comment]
Adding support for built-in audio is not currently planned. The vt1613 driver was never upstreamed and any version available would require reworking to be added into a modern kernel.
