### ISSUE TITLE
Battery info

### ISSUE THREAD

**Issue by pocketscience** [lrussell887/Debian-for-WM8505-Netbooks#4]
None of the typical battery info is available. I tried a few different options including UPower, batstat and none return anything. It looks like the details aren’t being made available. Has anyone had any luck? Given the age of these devices knowing the battery state would be very helpful.

**Comment by lrussell887** [comment]
Battery charge indication [was never added into the linux-vtwm kernel project](https://groups.google.com/g/vt8500-wm8505-linux-kernel/c/9uup5THe-SI/m/Yq27vP-vAAAJ), so I'm unfortunately unable to provide support for it now. If you are looking for general battery health information, there may be way to check from within Windows CE -- HPC:Factor is generally a good resource.

**Comment by pocketscience** [comment]
No problem, thanks for the quick response.
