### ISSUE TITLE
Accessing NAND memory

### ISSUE THREAD

**Issue by Aztorius** [lrussell887/Debian-for-WM8505-Netbooks#5]
Hello, great project !

I have successfully booted on this kind of Notebook with your project.

I am wondering if or how the soldered internal NAND memory is accessible (2GB TSOP-48) ? I could not find the device with lsblk (only the SD eMMC card).

Do you have any idea ?

Thank you.

**Comment by lrussell887** [comment]
NAND / serial flash support was never built into the linux-vtwm project, which this Debian build is based off of, so I'm unable to provide support for it now. Doing so is unfortunately outside of my skillset. 😅 Apologies.
